services:
  - type: web
    name: marseille-111-functions
    runtime: node
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p $PORT
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_EMAILS
        sync: false
