export const neighborhoodDescriptions: Record<string, string> = {
  belsunce: "Belsunce, c’est Marseille qui se croise et se mélange. Entre la Canebière, l’Alcazar et le marché du Soleil, le quartier vit au rythme de toute la Méditerranée.",
  "le-chapitre": "Le Chapitre, c’est le haut de la Canebière qui grimpe vers Saint-Charles. Les Réformés et le square Stalingrad lui donnent son allure de grand carrefour du centre.",
  noailles: "À Noailles, Marseille se raconte dans les odeurs, les couleurs et le bruit. Le marché des Capucins et la rue d’Aubagne font battre ce cœur populaire et méditerranéen.",
  opera: "Le quartier Opéra prolonge le Vieux-Port dans les petites rues du centre. On passe des terrasses d’Estienne-d’Orves à l’élégante façade de l’Opéra sans quitter l’agitation marseillaise.",
  "saint-charles": "Saint-Charles, c’est souvent la première image de Marseille quand on arrive en train. Depuis l’escalier monumental, toute la ville s’ouvre d’un coup jusqu’à la Bonne Mère.",
  thiers: "Thiers a gardé quelque chose du Marseille des théâtres et des lycées. Entre les Réformés, le Gymnase et le lycée Thiers, culture et vie étudiante se croisent chaque jour.",
  arenc: "Arenc, c’est un ancien quartier de docks qui change de visage. Le Silo et les tours d’Euroméditerranée racontent le passage du Marseille industriel à la ville d’aujourd’hui.",
  "grands-carmes": "Aux Grands-Carmes, les rues prennent vite de la hauteur. Entre la Halle Puget, la place Sadi-Carnot et les escaliers vers le port, on retrouve un Marseille dense et populaire.",
  "hotel-de-ville": "Hôtel-de-Ville, c’est le Marseille historique posé face aux bateaux. Derrière la mairie baroque, les ruelles du Panier et l’ancien Hôtel-Dieu racontent la plus vieille ville de France.",
  "la-joliette": "La Joliette, c’est le Marseille qui regarde vers le large : un ancien quartier de docks devenu l’un des coins les plus vivants du centre. Entre les vieilles pierres de la Major, les lignes du Mucem et le passé industriel des Docks, on passe d’une époque à l’autre en quelques rues.",
  "belle-de-mai": "La Belle de Mai, c’est un quartier ouvrier qui a transformé ses usines en lieux de création. L’ancienne manufacture des tabacs abrite aujourd’hui la Friche et toute son énergie culturelle.",
  "la-villette": "La Villette se trouve là où le centre rejoint les voies ferrées. Entre Saint-Charles, les anciens entrepôts et les routes vers le port, le quartier a toujours vécu dans le mouvement.",
  "saint-lazare": "Saint-Lazare, c’est un quartier de passage entre la gare et la Joliette. Le campus Saint-Charles et l’ancienne caserne du Muy donnent du relief à ce secteur en transformation.",
  "saint-mauront": "Saint-Mauront a grandi avec le rail, le port et les usines voisines. Sur la butte Bellevue, ce quartier populaire garde une identité forte dans un paysage qui bouge beaucoup.",
  "chutes-lavie": "Chutes-Lavie, c’est Marseille qui prend de la hauteur au-dessus du Jarret. Le canal, le parc et les escaliers montrent combien l’eau et le relief ont dessiné le quartier.",
  "cinq-avenues": "Cinq-Avenues, c’est le grand carrefour formé par les cinq axes qui lui donnent son nom. Le Palais Longchamp domine le quartier, pendant que le Pathé Madeleine et la place Sébastopol racontent sa vie quotidienne.",
  "la-blancarde": "La Blancarde, c’est un quartier résidentiel qui a toujours eu le goût du voyage. Sa gare, le tramway et le métro en font un grand point de passage de l’est marseillais.",
  "les-chartreux": "Les Chartreux ont gardé un vrai air de village autour de leur avenue. L’ancien monastère et son église ont donné leur nom à ce quartier qui descend vers le Jarret.",
  baille: "Baille, c’est ce long boulevard vivant qui relie Castellane à la Timone. Commerces, facultés et établissements de santé le font bouger du matin au soir.",
  "la-conception": "La Conception se glisse entre la Plaine, Baille et la Timone. Son grand hôpital rythme le quartier depuis le XIXe siècle et lui donne une identité très liée au soin.",
  "le-camas": "Le Camas, c’est un petit air de village à deux pas du centre. Boulevard Eugène-Pierre, le tramway passe entre les commerces, les maisons marseillaises et les terrasses.",
  "saint-pierre": "Saint-Pierre a gardé les traces de son ancien village malgré la ville tout autour. Son immense cimetière et le dépôt des tramways sont des repères connus de tous les Marseillais.",
  castellane: "Castellane, c’est le rond-point où Marseille part dans toutes les directions. La fontaine Cantini y a remplacé l’obélisque, transféré à Mazargues en 1911.",
  lodi: "Lodi, c’est un quartier où l’on vit beaucoup dehors. Sa longue rue commerçante relie Castellane à Notre-Dame-du-Mont entre balcons, petites places et bonnes adresses.",
  "notre-dame-du-mont": "Notre-Dame-du-Mont se découvre en montant, en descendant et en changeant d’ambiance. Les escaliers du Cours Julien mènent vers l’église, tandis que la passerelle de la rue d’Aubagne veille sur ce Marseille créatif.",
  "palais-de-justice": "Palais-de-Justice, c’est un centre-ville plus calme entre Estrangin et Vauban. Autour de la place Monthyon, le palais et les rues d’antiquaires lui donnent une élégance discrète.",
  prefecture: "Préfecture, c’est le Marseille des grandes façades et des rues bien alignées. L’hôtel préfectoral domine Félix-Baret, tandis que le tramway file rue de Rome vers Castellane.",
  vauban: "Vauban, ça grimpe, ça tourne et ça finit souvent avec une vue sur la Bonne Mère. Escaliers, petites maisons et places de quartier s’accrochent joyeusement à la colline.",
  bompard: "Bompard s’étage entre la Corniche et la Bonne Mère, avec la mer jamais très loin. Autour de Saint-Eugène, villas et jardins offrent un calme rare si près du centre.",
  endoume: "Endoume, c’est Marseille qui descend vers ses petits ports et ses rochers. Le Vallon des Auffes, Malmousque et leurs cabanons racontent un quartier tourné vers la mer.",
  "le-pharo": "Le Pharo avance dans la mer entre le Vieux-Port et les Catalans. Depuis le palais de Napoléon III et son jardin, la vue sur l’entrée du port est difficile à battre.",
  "les-iles": "Les Îles, c’est Marseille au large, avec du calcaire, du vent et beaucoup de bleu. Du château d’If à l’hôpital Caroline, le Frioul garde une histoire de défense et de quarantaine.",
  "roucas-blanc": "Le Roucas-Blanc s’accroche à la colline entre la Corniche et la Bonne Mère. Ses rues en lacets et ses escaliers ouvrent régulièrement des vues impressionnantes sur la rade.",
  "saint-lambert": "Saint-Lambert fait le lien entre la ville dense et le bord de mer. De la place du 4-Septembre aux Catalans, le quartier vit entre commerces, baignades et entrée du port.",
  "saint-victor": "Saint-Victor, c’est un des plus vieux morceaux de Marseille. Son abbaye, le fort Saint-Nicolas et l’odeur des navettes en février lui donnent une personnalité bien à lui.",
  bonneveine: "Bonneveine, c’est un grand morceau du sud où la ville respire. Entre le château Borély, les parcs et la route des plages, le quartier mélange culture, loisirs et quotidien.",
  "la-plage": "La Plage porte bien son nom : ici, Marseille vit face à la mer. Autour du David et des pelouses du Prado, on vient courir, se retrouver ou regarder la rade.",
  "le-rouet": "Le Rouet, c’est un quartier vivant entre Castellane, le Prado et l’Huveaune. Son église, ses commerces et ses anciens ateliers racontent un Marseille dense et toujours en mouvement.",
  "les-goudes": "Les Goudes, c’est le dernier village avant les calanques et presque un autre monde. Face à l’île Maïre, port, cabanons et roche blanche vivent au rythme du mistral.",
  montredon: "Montredon, c’est là où l’histoire industrielle rencontre les portes des calanques. Entre l’ancienne verrerie, la campagne Pastré et la mer, on passe de la brique aux pins.",
  perier: "Périer s’étend autour du Prado avec ses grandes avenues et ses immeubles élégants. Le Sacré-Cœur et les façades Art déco lui donnent son allure très reconnaissable.",
  "pointe-rouge": "Pointe-Rouge, c’est la plage, le port et le début de la route vers les Goudes. Voiliers, clubs nautiques et terrasses font vivre le quartier dès que le soleil revient.",
  "saint-giniez": "Saint-Giniez se trouve au croisement du Prado, de Borély et de Sainte-Anne. Le Vélodrome et le parc Chanot attirent les foules juste à côté de l’ancien village.",
  "sainte-anne": "Sainte-Anne, c’est un ancien village devenu un beau terrain de jeu pour l’architecture moderne. La Cité Radieuse y répond au Brasilia et à la villa Luce, sans faire oublier l’église qui a donné son nom au quartier.",
  "vieille-chapelle": "Vieille-Chapelle, c’est un quartier tranquille posé au bord de l’eau. Entre la petite anse, les plages et la Porte d’Orient, la promenade prend vite des airs de vacances.",
  carpiagne: "Carpiagne, c’est un immense morceau de collines à l’extrémité sud-est. Le camp militaire occupe l’essentiel de ce territoire où la ville laisse vite place à la garrigue.",
  "la-panouse": "La Panouse grimpe doucement vers les collines du sud. Bastides, restanques et pinèdes laissent encore deviner le passé rural derrière les résidences.",
  "le-cabot": "Le Cabot a gardé son petit cœur de village au milieu du sud résidentiel. Son église et le château de la Trignance rappellent l’époque où les bastides dominaient le paysage.",
  "le-redon": "Le Redon, c’est la ville qui monte jusqu’aux portes des calanques. Autour du campus de Luminy, étudiants et chercheurs vivent avec le mont Puget en toile de fond.",
  "les-baumettes": "Les Baumettes se trouvent là où Marseille commence à laisser place aux vallons. Le canal et la route de Sormiou racontent le quartier bien au-delà de sa célèbre prison.",
  mazargues: "Mazargues, c’est un ancien village de pêcheurs et de maraîchers devenu une porte des calanques. L’obélisque veille sur le quartier, pendant que Saint-Roch, le cimetière et la bastide Marcaggi racontent chacun leur histoire.",
  "sainte-marguerite": "Sainte-Marguerite a grandi autour d’un ancien village de l’Huveaune. Son église, l’hôpital Salvator et le stade Delort mêlent aujourd’hui vie résidentielle, soins et sport.",
  sormiou: "Sormiou, ce n’est pas seulement une calanque de carte postale : c’est tout un quartier qui descend vers elle. Au bout du vallon, cabanons et petit port se serrent entre les falaises.",
  vaufreges: "Vaufrèges, c’est Marseille côté nature, entre la Gineste et les massifs. La route serpente au milieu des bastides, des pins et de la roche jusqu’aux limites de Cassis.",
  "la-capelette": "La Capelette a longtemps vécu au rythme des usines et des anciens abattoirs. Aujourd’hui, la grande halle devenue patinoire raconte la nouvelle vie de ce quartier en mouvement.",
  "la-timone": "La Timone, c’est un quartier qui ne s’arrête jamais vraiment. Autour du grand hôpital, étudiants, soignants, métro et facultés font circuler Marseille à toute heure.",
  menpenti: "Menpenti se glisse entre le Prado, la Capelette et l’Huveaune. L’ancien marché aux bestiaux et le parc du 26e Centenaire voisin rappellent combien ce petit quartier a changé.",
  "pont-de-vivaux": "Pont-de-Vivaux est né autour d’un passage sur l’Huveaune et des routes vers l’est. L’hippodrome, les anciennes usines et la rivière gardent la mémoire de ce quartier de travail.",
  "saint-loup": "Saint-Loup a conservé son ancien village sur les hauteurs de l’Huveaune. Autour de l’église, les maisons racontent un quartier populaire longtemps partagé entre campagne et industrie.",
  "saint-tronc": "Saint-Tronc monte doucement vers le massif de Saint-Cyr. Son église, ses bastides et ses résidences composent un quartier calme où les collines restent toujours visibles.",
  eoures: "Éoures, c’est Marseille avec un vrai air de village provençal. Au pied des collines, l’église, les bastides et les chemins vers le Garlaban donnent l’impression d’avoir quitté la ville.",
  "la-barasse": "La Barasse se faufile entre l’Huveaune, le canal et Saint-Cyr. Sa gare, ses anciennes usines et ses carrières racontent un quartier industriel collé à la nature.",
  "la-milliere": "La Millière a gardé l’allure d’un village sur l’ancienne route d’Aubagne. Entre l’église, les maisons basses et la voie ferrée, le quartier vit à une échelle familière.",
  "la-pomme": "La Pomme s’est construite autour d’un ancien village près de l’Huveaune. Son église, sa gare et ses bastides rappellent qu’avant les routes, ici, c’était encore la campagne.",
  "la-treille": "La Treille, c’est un village perché face au Garlaban, inséparable de Marcel Pagnol. Sa fontaine, son église et le cimetière où il repose lui donnent un charme hors du temps.",
  "la-valbarelle": "La Valbarelle porte encore les traces du Marseille industriel de l’Huveaune. Anciennes usines, cités ouvrières et canal se retrouvent au pied des collines de Saint-Cyr.",
  "la-valentine": "La Valentine, c’est un ancien village rattrapé par les grandes zones commerciales. Derrière les enseignes, l’église Saint-Valentin et le château de la Buzine racontent une histoire bien plus ancienne.",
  "les-accates": "Les Accates ont gardé un esprit de village aux portes d’Allauch. Autour de Saint-Christophe, bastides, jardins et petites routes donnent au quartier une ambiance presque campagnarde.",
  "les-camoins": "Les Camoins, c’est un ancien village connu pour sa source thermale. L’église Sainte-Agathe, les platanes et les collines lui donnent une vraie douceur provençale.",
  "saint-marcel": "Saint-Marcel vit au bord de l’Huveaune, sous un oppidum antique. L’église, la gare et les anciennes usines racontent comment le village est devenu un grand quartier industriel.",
  "saint-menet": "Saint-Menet marque l’entrée de Marseille par la vallée de l’Huveaune. Le château de la Reynarde et les anciennes bastides se retrouvent aujourd’hui au milieu des zones d’activité.",
  "la-fourragere": "La Fourragère, c’est un quartier résidentiel posé sur d’anciennes terres agricoles. Métro, tramway et parc de la Mirabelle l’ont rapproché du centre sans lui enlever sa verdure.",
  "les-caillols": "Les Caillols ont gardé leur ancien village au milieu d’un quartier qui a beaucoup grandi. L’église, le château Saint-Julien et le tramway font se croiser patrimoine et Marseille d’aujourd’hui.",
  "les-trois-lucs": "Les Trois-Lucs, c’est un ancien hameau au croisement des routes de l’est. Autour de Sainte-Rita, bastides et pins annoncent déjà les collines d’Allauch.",
  montolivet: "Montolivet grimpe autour de son ancien village et de son avenue commerçante. L’église, les maisons avec jardin et le parc de la Moline lui donnent un côté tranquille.",
  "saint-barnabe": "Saint-Barnabé, c’est un village dans la ville, avec sa rue Montaigne et ses habitudes bien ancrées. L’église rappelle son passé, tandis que le métro le relie directement au centre.",
  "saint-jean-du-desert": "Saint-Jean-du-Désert a donné son nom à une célèbre faïence marseillaise. Entre l’église, le cimetière et le tramway, cet ancien chemin vers l’est continue de relier plusieurs Marseille.",
  "saint-julien": "Saint-Julien a gardé son petit noyau villageois sur les hauteurs. Autour de l’église, bastides et jardins donnent aux rues une ambiance calme et familière.",
  "chateau-gombert": "Château-Gombert, c’est un village provençal installé à côté d’un grand pôle scientifique. Le musée du Terroir et Saint-Matthieu racontent les traditions pendant que le technopôle regarde vers l’avenir.",
  "la-croix-rouge": "La Croix-Rouge se trouve tout au bout de Marseille, juste avant Allauch. Entre le château de la Rosière et les anciennes campagnes, la ville reste très proche des collines.",
  "la-rose": "La Rose, c’est un grand point de rendez-vous du nord-est marseillais. Le métro termine sa course près du canal, des résidences et de la route de Château-Gombert.",
  "les-medecins": "Les Médecins, c’est un Marseille discret installé dans les collines près d’Allauch. Anciens domaines et chemins bordés de végétation lui donnent un air de campagne.",
  "les-mourets": "Les Mourets se cachent dans les reliefs du nord-est, entre vallons et pinèdes. Bastides, restanques et chemins rappellent qu’ici, Marseille a longtemps été rurale.",
  "les-olives": "Les Olives ont conservé leur place, leur église et un vrai cœur de village. L’ancien moulin et les bastides racontent le passé agricole du quartier.",
  malpasse: "Malpassé s’étage dans un vallon du 13e, entre métro et grands ensembles. Le parc de Font-Obscure apporte un grand morceau de verdure à ce relief très urbain.",
  palama: "Palama se trouve au nord de Château-Gombert, face au massif de l’Étoile. Entre restanques, bastides et garrigue, c’est un coin où Marseille paraît encore presque rurale.",
  "saint-jerome": "Saint-Jérôme mélange un ancien village et un grand campus scientifique. L’église, les laboratoires et l’École centrale vivent avec les collines en toile de fond.",
  "saint-just": "Saint-Just, c’est un carrefour où beaucoup de Marseillais passent chaque jour. Le Dôme et l’Hôtel du Département imposent leurs formes modernes au-dessus du métro.",
  "saint-mitre": "Saint-Mitre a grandi autour d’anciennes bastides sur les hauteurs. Son église, ses jardins et ses équipements sportifs ouvrent le quartier vers le massif de l’Étoile.",
  "bon-secours": "Bon-Secours grimpe sur une colline du nord avec le port en ligne de mire. Autour de l’église, cités et escaliers racontent un quartier profondément populaire.",
  "le-canet": "Le Canet a grandi avec les trains, les entrepôts et les usines. La gare de marchandises rappelle encore cette histoire dans un quartier aujourd’hui très habité.",
  "le-merlan": "Le Merlan, c’est un quartier de grands ensembles qui a fait une vraie place à la culture. Sa scène nationale donne rendez-vous au théâtre, aux étudiants et aux habitants.",
  "les-arnavaux": "Aux Arnavaux, Marseille travaille et circule à grande échelle. Le marché d’intérêt national, les hangars et les autoroutes donnent au quartier son énergie logistique.",
  "saint-barthelemy": "Saint-Barthélemy est immense, avec ses anciens domaines, ses maisons et ses grandes cités. Le château de Fontainieu et Font-Obscure gardent quelques traces du paysage d’autrefois.",
  "saint-joseph": "Saint-Joseph s’est installé sur les hauteurs autour de son ancien village. L’église et le château Ricard rappellent le temps des grandes propriétés.",
  "sainte-marthe": "Sainte-Marthe, c’est un village, une gare et tout un quartier construit autour. Le domaine de Tour-Sainte raconte un nord marseillais longtemps tourné vers l’agriculture.",
  "la-cabucelle": "La Cabucelle a grandi avec le port, les ateliers et les usines. Saint-Trophime et les anciennes friches racontent encore la vie ouvrière du quartier.",
  "la-calade": "La Calade prend de la hauteur au-dessus des bassins du port. Entre le château Bovis, l’église et les cheminées industrielles, le quartier garde un œil sur la rade.",
  "la-delorme": "La Delorme se trouve entre les quartiers nord et les grandes routes qui quittent Marseille. Derrière les lotissements, le canal et les anciennes campagnes réapparaissent encore par endroits.",
  "la-viste": "La Viste porte bien son nom : depuis la colline, Marseille et sa rade s’ouvrent largement. L’église et les grands ensembles dominent l’ancienne route du nord.",
  "les-aygalades": "Les Aygalades cachent une cascade que beaucoup de Marseillais ne connaissent pas. Entre le ruisseau, les anciennes fabriques et la Cité des arts de la rue, nature et création se rencontrent.",
  "les-borels": "Les Borels, c’est un ancien hameau au pied du massif de l’Étoile. Chapelle, bastides et chemins de garrigue lui donnent des airs de village loin du centre.",
  "les-crottes": "Les Crottes se trouvent juste derrière le port, dans un territoire industriel qui change vite. Entrepôts, marché aux puces et chantiers d’Euroméditerranée racontent plusieurs époques du quartier.",
  "notre-dame-limite": "Notre-Dame-Limite, c’est vraiment le bout de Marseille, juste avant Septèmes. L’église, l’hôpital Nord et les routes vers Aix lui donnent un vrai rôle de porte de la ville.",
  "saint-antoine": "Saint-Antoine a grandi sur l’ancienne route d’Aix et garde un cœur de village. Sa gare, son église et l’hôpital Nord en font un point d’entrée majeur de Marseille.",
  "saint-louis": "Saint-Louis, c’est un ancien village devenu quartier ouvrier avec les usines et le port. Son église néogothique et le château Saint-Louis émergent encore dans ce paysage industriel.",
  verduron: "Verduron domine la rade depuis une colline du nord-ouest. Tout en haut, l’oppidum rappelle que l’endroit était déjà habité il y a plus de deux mille ans.",
  "l-estaque": "L’Estaque, c’est un port, des collines et une lumière qui a attiré Cézanne ou Braque. Les tuileries racontent le travail d’hier, les chichis et panisses font vivre le village d’aujourd’hui.",
  "les-riaux": "Les Riaux se glissent dans un vallon entre l’Estaque, les carrières et la mer. Viaduc, rails et anciennes usines lui donnent un décor brut, directement lié à son histoire ouvrière.",
  "saint-andre": "Saint-André a grandi autour d’un village et des tuileries du bassin de Séon. L’église, le château et les cheminées racontent le passage de la campagne au Marseille industriel.",
  "saint-henri": "Saint-Henri a gardé son cœur de village au milieu de l’ancien bassin des tuileries. Son église, les rails et les usines rappellent les générations d’ouvriers qui l’ont façonné."
};
