ALTER TABLE proposals ADD COLUMN publish_instagram INTEGER NOT NULL DEFAULT 1;
ALTER TABLE proposals ADD COLUMN publish_tiktok INTEGER NOT NULL DEFAULT 1;
ALTER TABLE proposals ADD COLUMN publish_x INTEGER NOT NULL DEFAULT 1;
